pub const AutoGenerated = struct {
    album_type: []u8,
    total_tracks: i32,
    available_markets: [][]u8,

    href: []u8,
    id: []u8,
    images: []Images,
    name: []u8,
    release_date: []u8,
    release_date_precision: []u8,
    type: []u8,
    uri: []u8,
    artists: []Artists,
    tracks: Tracks,
};
const External_Urls = struct {
    spotify: []u8,
};
const Images = struct {
    url: []u8,
    height: i32,
    width: i32,
};
const Artists = struct {
    href: []u8,
    id: []u8,
    name: []u8,
    uri: []u8,
};
const Items = struct {
    artists: []Artists,
    available_markets: [][]u8,
    disc_number: i32,
    duration_ms: i32,
    explicit: bool,
    external_urls: External_Urls,
    href: []u8,
    id: []u8,
    name: []u8,
    preview_url: ?[]u8,
    track_number: i32,
    type: []u8,
    uri: []u8,
    is_local: bool,
};
const Tracks = struct {
    href: []u8,

    offset: i32,

    total: i32,
};
const Copyrights = struct {
    text: []u8,
    type: []u8,
};
const External_Ids = struct {
    upc: []u8,
};
